<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7c8913f8-ca68-46b0-869e-8df420903166}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbIO	: FB_IOManager;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbIO();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>