<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MeasureUnits_to_Count" Id="{b1349917-8af6-4438-86a4-6346e1c26277}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION MeasureUnits_to_Count : int;
VAR_INPUT
	iValue_in	: REAL; 
	iHigh		: REAL;
	iLow		: REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MeasureUnits_to_Count	:=	TO_INT(((iValue_In) - iLow)*(32767.0/(iHigh - iLow)));]]></ST>
    </Implementation>
    <LineIds Name="MeasureUnits_to_Count">
      <LineId Id="26" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>